# Generated by Django 5.2.15 on 2026-06-18 00:33

import medicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("fecha_de_alta", models.DateField(auto_now_add=True)),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("Rama del corazon", "Cardiologo"),
                            ("Rama de los huevos", "Traumatologo"),
                            ("Rama del cerebro", "Neurologo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=medicos.models.generar_code, max_length=32, unique=True
                    ),
                ),
                ("dni", models.CharField(max_length=12)),
                ("nro_medico", models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
