# Generated by Django 5.2.15 on 2026-06-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicos",
            name="telefono",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
