# Generated by Django 5.2.15 on 2026-06-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0002_medicos_telefono"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicos",
            name="telefono",
        ),
    ]
