# Generated by Django 5.2.15 on 2026-07-02 01:02

import medicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pacientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("dni", models.CharField(max_length=12, unique=True)),
                (
                    "code",
                    models.CharField(
                        default=medicos.models.generar_code, max_length=32, unique=True
                    ),
                ),
                ("telefono", models.CharField(max_length=20)),
            ],
        ),
    ]
